
part of "FormTwoModel.dart";
/// This file contains the code that's generated by json_serializable.
/// It's necessary for serialization and deserialization to work properly.

FormTwoModel _$FormTwoModelFromJson(Map<String, dynamic> json) {
  return FormTwoModel(
    ownerName: json['ownerName'] as String?,
    ownerFatherName: json['ownerFatherName'] as String?,
    cnic: json['cnic'] as String?,
    cellNo: json['cellNo'] as String?,
    contactPerson1: json['contactPerson1'] as String?,
    contactPerson1CellNum: json['contactPerson1CellNum'] as String?,
    contactPerson2: json['contactPerson2'] as String?,
    contactPerson2CellNum: json['contactPerson2CellNum'] as String?,
    contactPerson3: json['contactPerson3'] as String?,
    contactPerson3CellNum: json['contactPerson3CellNum'] as String?,
    frontImage: json['fontImage'] as String?,
    backImage: json['backImage'] as String?,
    signature: json['signature'] as String?,
    outletImage: json['outletImage'] as String?,
  );
}

Map<String, dynamic> _$FormTwoModelToJson(FormTwoModel instance) =>
    <String, dynamic>{
      'ownerName': instance.ownerName,
      'ownerFatherName': instance.ownerFatherName,
      'cnic': instance.cnic,
      'cellNo': instance.cellNo,
      'contactPerson1': instance.contactPerson1,
      'contactPerson1CellNum': instance.contactPerson1CellNum,
      'contactPerson2': instance.contactPerson2,
      'contactPerson2CellNum': instance.contactPerson2CellNum,
      'contactPerson3': instance.contactPerson3,
      'contactPerson3CellNum': instance.contactPerson3CellNum,
      'fontImage': instance.frontImage,
      'backImage': instance.backImage,
      'signature': instance.signature,
      'outletImage': instance.outletImage,
    };
